### ISSUE TITLE
Allow setting of a global default env

### ISSUE THREAD

**Issue by mjtko** [openflighthpc/flight-env#6]
Allow superuser to set global default env that is activated by default for all users.

Each user should be able to override to a different default or remove the default.

**Comment by ColonelPanicks** [comment]
This feature would be useful, especially in recent months there have been times where setting a global user default would save time during user creation!

**Comment by benarmston** [comment]
Fixed in #8.  It will be released with user suite 2022.4

* A cluster admin can set a *global* environment as the system-wide default with `flenv set-default --system ENV`.
* A cluster admin can remove the system-wide default with `flenv remove-default --system`.
* A user can set their own default with `flenv set-default ENV`.
* A user can use the system-wide default (if any) with `flenv set-default --use-system`.
* A user can remove their default (ignoring any system-wide default) with `flenv remove-default`.
